# fly.toml app configuration file generated for mkumm-blog on 2024-04-13T22:41:19+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mkumm-blog'
primary_region = 'waw'

[build]

[http_service]
#internal_port = 8043
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[mounts]
  source="config_data"
  destination="/config_data"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

  
